// Generated by gencpp from file utils/go_toRequest.msg
// DO NOT EDIT!


#ifndef UTILS_MESSAGE_GO_TOREQUEST_H
#define UTILS_MESSAGE_GO_TOREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace utils
{
template <class ContainerAllocator>
struct go_toRequest_
{
  typedef go_toRequest_<ContainerAllocator> Type;

  go_toRequest_()
    : vrefName()
    , x0(0.0)
    , y0(0.0)
    , yaw0(0.0)
    , dest_x(0.0)
    , dest_y(0.0)  {
    }
  go_toRequest_(const ContainerAllocator& _alloc)
    : vrefName(_alloc)
    , x0(0.0)
    , y0(0.0)
    , yaw0(0.0)
    , dest_x(0.0)
    , dest_y(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _vrefName_type;
  _vrefName_type vrefName;

   typedef double _x0_type;
  _x0_type x0;

   typedef double _y0_type;
  _y0_type y0;

   typedef double _yaw0_type;
  _yaw0_type yaw0;

   typedef double _dest_x_type;
  _dest_x_type dest_x;

   typedef double _dest_y_type;
  _dest_y_type dest_y;





  typedef boost::shared_ptr< ::utils::go_toRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::utils::go_toRequest_<ContainerAllocator> const> ConstPtr;

}; // struct go_toRequest_

typedef ::utils::go_toRequest_<std::allocator<void> > go_toRequest;

typedef boost::shared_ptr< ::utils::go_toRequest > go_toRequestPtr;
typedef boost::shared_ptr< ::utils::go_toRequest const> go_toRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::utils::go_toRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::utils::go_toRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::utils::go_toRequest_<ContainerAllocator1> & lhs, const ::utils::go_toRequest_<ContainerAllocator2> & rhs)
{
  return lhs.vrefName == rhs.vrefName &&
    lhs.x0 == rhs.x0 &&
    lhs.y0 == rhs.y0 &&
    lhs.yaw0 == rhs.yaw0 &&
    lhs.dest_x == rhs.dest_x &&
    lhs.dest_y == rhs.dest_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::utils::go_toRequest_<ContainerAllocator1> & lhs, const ::utils::go_toRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::utils::go_toRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::go_toRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::go_toRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::go_toRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::go_toRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::go_toRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::utils::go_toRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "27b9a2816bf2f0ac88230b35ccc261d4";
  }

  static const char* value(const ::utils::go_toRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x27b9a2816bf2f0acULL;
  static const uint64_t static_value2 = 0x88230b35ccc261d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::utils::go_toRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "utils/go_toRequest";
  }

  static const char* value(const ::utils::go_toRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::utils::go_toRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request\n"
"string vrefName\n"
"float64 x0\n"
"float64 y0\n"
"float64 yaw0\n"
"float64 dest_x\n"
"float64 dest_y\n"
;
  }

  static const char* value(const ::utils::go_toRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::utils::go_toRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vrefName);
      stream.next(m.x0);
      stream.next(m.y0);
      stream.next(m.yaw0);
      stream.next(m.dest_x);
      stream.next(m.dest_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct go_toRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::utils::go_toRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::utils::go_toRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "vrefName: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.vrefName);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "x0: ";
    Printer<double>::stream(s, indent + "  ", v.x0);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y0: ";
    Printer<double>::stream(s, indent + "  ", v.y0);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "yaw0: ";
    Printer<double>::stream(s, indent + "  ", v.yaw0);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "dest_x: ";
    Printer<double>::stream(s, indent + "  ", v.dest_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "dest_y: ";
    Printer<double>::stream(s, indent + "  ", v.dest_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTILS_MESSAGE_GO_TOREQUEST_H
