// Generated by gencpp from file utils/go_to.msg
// DO NOT EDIT!


#ifndef UTILS_MESSAGE_GO_TO_H
#define UTILS_MESSAGE_GO_TO_H

#include <ros/service_traits.h>


#include <utils/go_toRequest.h>
#include <utils/go_toResponse.h>


namespace utils
{

struct go_to
{

typedef go_toRequest Request;
typedef go_toResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct go_to
} // namespace utils


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::utils::go_to > {
  static const char* value()
  {
    return "eafc11809102a127427b195870ef5f28";
  }

  static const char* value(const ::utils::go_to&) { return value(); }
};

template<>
struct DataType< ::utils::go_to > {
  static const char* value()
  {
    return "utils/go_to";
  }

  static const char* value(const ::utils::go_to&) { return value(); }
};


// service_traits::MD5Sum< ::utils::go_toRequest> should match
// service_traits::MD5Sum< ::utils::go_to >
template<>
struct MD5Sum< ::utils::go_toRequest>
{
  static const char* value()
  {
    return MD5Sum< ::utils::go_to >::value();
  }
  static const char* value(const ::utils::go_toRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::utils::go_toRequest> should match
// service_traits::DataType< ::utils::go_to >
template<>
struct DataType< ::utils::go_toRequest>
{
  static const char* value()
  {
    return DataType< ::utils::go_to >::value();
  }
  static const char* value(const ::utils::go_toRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::utils::go_toResponse> should match
// service_traits::MD5Sum< ::utils::go_to >
template<>
struct MD5Sum< ::utils::go_toResponse>
{
  static const char* value()
  {
    return MD5Sum< ::utils::go_to >::value();
  }
  static const char* value(const ::utils::go_toResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::utils::go_toResponse> should match
// service_traits::DataType< ::utils::go_to >
template<>
struct DataType< ::utils::go_toResponse>
{
  static const char* value()
  {
    return DataType< ::utils::go_to >::value();
  }
  static const char* value(const ::utils::go_toResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UTILS_MESSAGE_GO_TO_H
