// Generated by gencpp from file utils/go_to_multipleRequest.msg
// DO NOT EDIT!


#ifndef UTILS_MESSAGE_GO_TO_MULTIPLEREQUEST_H
#define UTILS_MESSAGE_GO_TO_MULTIPLEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <utils/Point2D.h>

namespace utils
{
template <class ContainerAllocator>
struct go_to_multipleRequest_
{
  typedef go_to_multipleRequest_<ContainerAllocator> Type;

  go_to_multipleRequest_()
    : vrefName()
    , x0(0.0)
    , y0(0.0)
    , yaw0(0.0)
    , destinations()  {
    }
  go_to_multipleRequest_(const ContainerAllocator& _alloc)
    : vrefName(_alloc)
    , x0(0.0)
    , y0(0.0)
    , yaw0(0.0)
    , destinations(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _vrefName_type;
  _vrefName_type vrefName;

   typedef double _x0_type;
  _x0_type x0;

   typedef double _y0_type;
  _y0_type y0;

   typedef double _yaw0_type;
  _yaw0_type yaw0;

   typedef std::vector< ::utils::Point2D_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::utils::Point2D_<ContainerAllocator> >> _destinations_type;
  _destinations_type destinations;





  typedef boost::shared_ptr< ::utils::go_to_multipleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::utils::go_to_multipleRequest_<ContainerAllocator> const> ConstPtr;

}; // struct go_to_multipleRequest_

typedef ::utils::go_to_multipleRequest_<std::allocator<void> > go_to_multipleRequest;

typedef boost::shared_ptr< ::utils::go_to_multipleRequest > go_to_multipleRequestPtr;
typedef boost::shared_ptr< ::utils::go_to_multipleRequest const> go_to_multipleRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::utils::go_to_multipleRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::utils::go_to_multipleRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::utils::go_to_multipleRequest_<ContainerAllocator1> & lhs, const ::utils::go_to_multipleRequest_<ContainerAllocator2> & rhs)
{
  return lhs.vrefName == rhs.vrefName &&
    lhs.x0 == rhs.x0 &&
    lhs.y0 == rhs.y0 &&
    lhs.yaw0 == rhs.yaw0 &&
    lhs.destinations == rhs.destinations;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::utils::go_to_multipleRequest_<ContainerAllocator1> & lhs, const ::utils::go_to_multipleRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::utils::go_to_multipleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::go_to_multipleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::go_to_multipleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::go_to_multipleRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::go_to_multipleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::go_to_multipleRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::utils::go_to_multipleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f2759900116fce48a9130da8a42d76ae";
  }

  static const char* value(const ::utils::go_to_multipleRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf2759900116fce48ULL;
  static const uint64_t static_value2 = 0xa9130da8a42d76aeULL;
};

template<class ContainerAllocator>
struct DataType< ::utils::go_to_multipleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "utils/go_to_multipleRequest";
  }

  static const char* value(const ::utils::go_to_multipleRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::utils::go_to_multipleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request\n"
"string vrefName\n"
"float64 x0\n"
"float64 y0\n"
"float64 yaw0\n"
"Point2D[] destinations\n"
"\n"
"================================================================================\n"
"MSG: utils/Point2D\n"
"float32 x\n"
"float32 y\n"
;
  }

  static const char* value(const ::utils::go_to_multipleRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::utils::go_to_multipleRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vrefName);
      stream.next(m.x0);
      stream.next(m.y0);
      stream.next(m.yaw0);
      stream.next(m.destinations);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct go_to_multipleRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::utils::go_to_multipleRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::utils::go_to_multipleRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "vrefName: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.vrefName);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "x0: ";
    Printer<double>::stream(s, indent + "  ", v.x0);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y0: ";
    Printer<double>::stream(s, indent + "  ", v.y0);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "yaw0: ";
    Printer<double>::stream(s, indent + "  ", v.yaw0);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "destinations: ";
    if (v.destinations.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.destinations.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::utils::Point2D_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.destinations[i]);
    }
    if (v.destinations.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTILS_MESSAGE_GO_TO_MULTIPLEREQUEST_H
