// Generated by gencpp from file utils/go_to_multiple.msg
// DO NOT EDIT!


#ifndef UTILS_MESSAGE_GO_TO_MULTIPLE_H
#define UTILS_MESSAGE_GO_TO_MULTIPLE_H

#include <ros/service_traits.h>


#include <utils/go_to_multipleRequest.h>
#include <utils/go_to_multipleResponse.h>


namespace utils
{

struct go_to_multiple
{

typedef go_to_multipleRequest Request;
typedef go_to_multipleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct go_to_multiple
} // namespace utils


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::utils::go_to_multiple > {
  static const char* value()
  {
    return "3e9590ffda7f3c098d288272e4eaaa2d";
  }

  static const char* value(const ::utils::go_to_multiple&) { return value(); }
};

template<>
struct DataType< ::utils::go_to_multiple > {
  static const char* value()
  {
    return "utils/go_to_multiple";
  }

  static const char* value(const ::utils::go_to_multiple&) { return value(); }
};


// service_traits::MD5Sum< ::utils::go_to_multipleRequest> should match
// service_traits::MD5Sum< ::utils::go_to_multiple >
template<>
struct MD5Sum< ::utils::go_to_multipleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::utils::go_to_multiple >::value();
  }
  static const char* value(const ::utils::go_to_multipleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::utils::go_to_multipleRequest> should match
// service_traits::DataType< ::utils::go_to_multiple >
template<>
struct DataType< ::utils::go_to_multipleRequest>
{
  static const char* value()
  {
    return DataType< ::utils::go_to_multiple >::value();
  }
  static const char* value(const ::utils::go_to_multipleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::utils::go_to_multipleResponse> should match
// service_traits::MD5Sum< ::utils::go_to_multiple >
template<>
struct MD5Sum< ::utils::go_to_multipleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::utils::go_to_multiple >::value();
  }
  static const char* value(const ::utils::go_to_multipleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::utils::go_to_multipleResponse> should match
// service_traits::DataType< ::utils::go_to_multiple >
template<>
struct DataType< ::utils::go_to_multipleResponse>
{
  static const char* value()
  {
    return DataType< ::utils::go_to_multiple >::value();
  }
  static const char* value(const ::utils::go_to_multipleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UTILS_MESSAGE_GO_TO_MULTIPLE_H
