// Generated by gencpp from file utils/goto_commandResponse.msg
// DO NOT EDIT!


#ifndef UTILS_MESSAGE_GOTO_COMMANDRESPONSE_H
#define UTILS_MESSAGE_GOTO_COMMANDRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float32MultiArray.h>
#include <std_msgs/Float32MultiArray.h>
#include <std_msgs/Float32MultiArray.h>
#include <std_msgs/Float32MultiArray.h>

namespace utils
{
template <class ContainerAllocator>
struct goto_commandResponse_
{
  typedef goto_commandResponse_<ContainerAllocator> Type;

  goto_commandResponse_()
    : state_refs()
    , input_refs()
    , wp_attributes()
    , wp_normals()
    , success(false)  {
    }
  goto_commandResponse_(const ContainerAllocator& _alloc)
    : state_refs(_alloc)
    , input_refs(_alloc)
    , wp_attributes(_alloc)
    , wp_normals(_alloc)
    , success(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Float32MultiArray_<ContainerAllocator>  _state_refs_type;
  _state_refs_type state_refs;

   typedef  ::std_msgs::Float32MultiArray_<ContainerAllocator>  _input_refs_type;
  _input_refs_type input_refs;

   typedef  ::std_msgs::Float32MultiArray_<ContainerAllocator>  _wp_attributes_type;
  _wp_attributes_type wp_attributes;

   typedef  ::std_msgs::Float32MultiArray_<ContainerAllocator>  _wp_normals_type;
  _wp_normals_type wp_normals;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::utils::goto_commandResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::utils::goto_commandResponse_<ContainerAllocator> const> ConstPtr;

}; // struct goto_commandResponse_

typedef ::utils::goto_commandResponse_<std::allocator<void> > goto_commandResponse;

typedef boost::shared_ptr< ::utils::goto_commandResponse > goto_commandResponsePtr;
typedef boost::shared_ptr< ::utils::goto_commandResponse const> goto_commandResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::utils::goto_commandResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::utils::goto_commandResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::utils::goto_commandResponse_<ContainerAllocator1> & lhs, const ::utils::goto_commandResponse_<ContainerAllocator2> & rhs)
{
  return lhs.state_refs == rhs.state_refs &&
    lhs.input_refs == rhs.input_refs &&
    lhs.wp_attributes == rhs.wp_attributes &&
    lhs.wp_normals == rhs.wp_normals &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::utils::goto_commandResponse_<ContainerAllocator1> & lhs, const ::utils::goto_commandResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::utils::goto_commandResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::goto_commandResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::goto_commandResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::goto_commandResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::goto_commandResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::goto_commandResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::utils::goto_commandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "10cf1e165cb42339ea4b19231cd1b671";
  }

  static const char* value(const ::utils::goto_commandResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x10cf1e165cb42339ULL;
  static const uint64_t static_value2 = 0xea4b19231cd1b671ULL;
};

template<class ContainerAllocator>
struct DataType< ::utils::goto_commandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "utils/goto_commandResponse";
  }

  static const char* value(const ::utils::goto_commandResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::utils::goto_commandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Response\n"
"std_msgs/Float32MultiArray state_refs\n"
"std_msgs/Float32MultiArray input_refs\n"
"std_msgs/Float32MultiArray wp_attributes\n"
"std_msgs/Float32MultiArray wp_normals\n"
"bool success\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float32MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"float32[]         data          # array of data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayLayout\n"
"# The multiarray declares a generic multi-dimensional array of a\n"
"# particular data type.  Dimensions are ordered from outer most\n"
"# to inner most.\n"
"\n"
"MultiArrayDimension[] dim # Array of dimension properties\n"
"uint32 data_offset        # padding elements at front of data\n"
"\n"
"# Accessors should ALWAYS be written in terms of dimension stride\n"
"# and specified outer-most dimension first.\n"
"# \n"
"# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n"
"#\n"
"# A standard, 3-channel 640x480 image with interleaved color channels\n"
"# would be specified as:\n"
"#\n"
"# dim[0].label  = \"height\"\n"
"# dim[0].size   = 480\n"
"# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n"
"# dim[1].label  = \"width\"\n"
"# dim[1].size   = 640\n"
"# dim[1].stride = 3*640 = 1920\n"
"# dim[2].label  = \"channel\"\n"
"# dim[2].size   = 3\n"
"# dim[2].stride = 3\n"
"#\n"
"# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayDimension\n"
"string label   # label of given dimension\n"
"uint32 size    # size of given dimension (in type units)\n"
"uint32 stride  # stride of given dimension\n"
;
  }

  static const char* value(const ::utils::goto_commandResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::utils::goto_commandResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state_refs);
      stream.next(m.input_refs);
      stream.next(m.wp_attributes);
      stream.next(m.wp_normals);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct goto_commandResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::utils::goto_commandResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::utils::goto_commandResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "state_refs: ";
    Printer< ::std_msgs::Float32MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.state_refs);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "input_refs: ";
    Printer< ::std_msgs::Float32MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.input_refs);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "wp_attributes: ";
    Printer< ::std_msgs::Float32MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.wp_attributes);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "wp_normals: ";
    Printer< ::std_msgs::Float32MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.wp_normals);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTILS_MESSAGE_GOTO_COMMANDRESPONSE_H
