// Generated by gencpp from file utils/goto_command.msg
// DO NOT EDIT!


#ifndef UTILS_MESSAGE_GOTO_COMMAND_H
#define UTILS_MESSAGE_GOTO_COMMAND_H

#include <ros/service_traits.h>


#include <utils/goto_commandRequest.h>
#include <utils/goto_commandResponse.h>


namespace utils
{

struct goto_command
{

typedef goto_commandRequest Request;
typedef goto_commandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct goto_command
} // namespace utils


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::utils::goto_command > {
  static const char* value()
  {
    return "9b99b56ad3b4e93a7deab6c9c680fa9c";
  }

  static const char* value(const ::utils::goto_command&) { return value(); }
};

template<>
struct DataType< ::utils::goto_command > {
  static const char* value()
  {
    return "utils/goto_command";
  }

  static const char* value(const ::utils::goto_command&) { return value(); }
};


// service_traits::MD5Sum< ::utils::goto_commandRequest> should match
// service_traits::MD5Sum< ::utils::goto_command >
template<>
struct MD5Sum< ::utils::goto_commandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::utils::goto_command >::value();
  }
  static const char* value(const ::utils::goto_commandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::utils::goto_commandRequest> should match
// service_traits::DataType< ::utils::goto_command >
template<>
struct DataType< ::utils::goto_commandRequest>
{
  static const char* value()
  {
    return DataType< ::utils::goto_command >::value();
  }
  static const char* value(const ::utils::goto_commandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::utils::goto_commandResponse> should match
// service_traits::MD5Sum< ::utils::goto_command >
template<>
struct MD5Sum< ::utils::goto_commandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::utils::goto_command >::value();
  }
  static const char* value(const ::utils::goto_commandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::utils::goto_commandResponse> should match
// service_traits::DataType< ::utils::goto_command >
template<>
struct DataType< ::utils::goto_commandResponse>
{
  static const char* value()
  {
    return DataType< ::utils::goto_command >::value();
  }
  static const char* value(const ::utils::goto_commandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UTILS_MESSAGE_GOTO_COMMAND_H
