// Generated by gencpp from file utils/goto_commandRequest.msg
// DO NOT EDIT!


#ifndef UTILS_MESSAGE_GOTO_COMMANDREQUEST_H
#define UTILS_MESSAGE_GOTO_COMMANDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace utils
{
template <class ContainerAllocator>
struct goto_commandRequest_
{
  typedef goto_commandRequest_<ContainerAllocator> Type;

  goto_commandRequest_()
    : dest_x(0.0)
    , dest_y(0.0)  {
    }
  goto_commandRequest_(const ContainerAllocator& _alloc)
    : dest_x(0.0)
    , dest_y(0.0)  {
  (void)_alloc;
    }



   typedef double _dest_x_type;
  _dest_x_type dest_x;

   typedef double _dest_y_type;
  _dest_y_type dest_y;





  typedef boost::shared_ptr< ::utils::goto_commandRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::utils::goto_commandRequest_<ContainerAllocator> const> ConstPtr;

}; // struct goto_commandRequest_

typedef ::utils::goto_commandRequest_<std::allocator<void> > goto_commandRequest;

typedef boost::shared_ptr< ::utils::goto_commandRequest > goto_commandRequestPtr;
typedef boost::shared_ptr< ::utils::goto_commandRequest const> goto_commandRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::utils::goto_commandRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::utils::goto_commandRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::utils::goto_commandRequest_<ContainerAllocator1> & lhs, const ::utils::goto_commandRequest_<ContainerAllocator2> & rhs)
{
  return lhs.dest_x == rhs.dest_x &&
    lhs.dest_y == rhs.dest_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::utils::goto_commandRequest_<ContainerAllocator1> & lhs, const ::utils::goto_commandRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::utils::goto_commandRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::goto_commandRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::goto_commandRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::goto_commandRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::goto_commandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::goto_commandRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::utils::goto_commandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e28e8b7f11b48213f87e173dd7e1804a";
  }

  static const char* value(const ::utils::goto_commandRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe28e8b7f11b48213ULL;
  static const uint64_t static_value2 = 0xf87e173dd7e1804aULL;
};

template<class ContainerAllocator>
struct DataType< ::utils::goto_commandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "utils/goto_commandRequest";
  }

  static const char* value(const ::utils::goto_commandRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::utils::goto_commandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request\n"
"float64 dest_x\n"
"float64 dest_y\n"
;
  }

  static const char* value(const ::utils::goto_commandRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::utils::goto_commandRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dest_x);
      stream.next(m.dest_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct goto_commandRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::utils::goto_commandRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::utils::goto_commandRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "dest_x: ";
    Printer<double>::stream(s, indent + "  ", v.dest_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "dest_y: ";
    Printer<double>::stream(s, indent + "  ", v.dest_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTILS_MESSAGE_GOTO_COMMANDREQUEST_H
