// Generated by gencpp from file utils/Lane3.msg
// DO NOT EDIT!


#ifndef UTILS_MESSAGE_LANE3_H
#define UTILS_MESSAGE_LANE3_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace utils
{
template <class ContainerAllocator>
struct Lane3_
{
  typedef Lane3_<ContainerAllocator> Type;

  Lane3_()
    : header()
    , lane_center_offset(0.0)
    , stopline_dist(0.0)
    , stopline_angle(0.0)
    , lane_waypoints()
    , left_waypoints()
    , right_waypoints()
    , good_left(false)
    , good_right(false)
    , near_m(0.0)
    , straight_lane(false)
    , straight_lane_angle(0.0)  {
    }
  Lane3_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , lane_center_offset(0.0)
    , stopline_dist(0.0)
    , stopline_angle(0.0)
    , lane_waypoints(_alloc)
    , left_waypoints(_alloc)
    , right_waypoints(_alloc)
    , good_left(false)
    , good_right(false)
    , near_m(0.0)
    , straight_lane(false)
    , straight_lane_angle(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _lane_center_offset_type;
  _lane_center_offset_type lane_center_offset;

   typedef float _stopline_dist_type;
  _stopline_dist_type stopline_dist;

   typedef float _stopline_angle_type;
  _stopline_angle_type stopline_angle;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _lane_waypoints_type;
  _lane_waypoints_type lane_waypoints;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _left_waypoints_type;
  _left_waypoints_type left_waypoints;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _right_waypoints_type;
  _right_waypoints_type right_waypoints;

   typedef uint8_t _good_left_type;
  _good_left_type good_left;

   typedef uint8_t _good_right_type;
  _good_right_type good_right;

   typedef float _near_m_type;
  _near_m_type near_m;

   typedef uint8_t _straight_lane_type;
  _straight_lane_type straight_lane;

   typedef float _straight_lane_angle_type;
  _straight_lane_angle_type straight_lane_angle;





  typedef boost::shared_ptr< ::utils::Lane3_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::utils::Lane3_<ContainerAllocator> const> ConstPtr;

}; // struct Lane3_

typedef ::utils::Lane3_<std::allocator<void> > Lane3;

typedef boost::shared_ptr< ::utils::Lane3 > Lane3Ptr;
typedef boost::shared_ptr< ::utils::Lane3 const> Lane3ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::utils::Lane3_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::utils::Lane3_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::utils::Lane3_<ContainerAllocator1> & lhs, const ::utils::Lane3_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.lane_center_offset == rhs.lane_center_offset &&
    lhs.stopline_dist == rhs.stopline_dist &&
    lhs.stopline_angle == rhs.stopline_angle &&
    lhs.lane_waypoints == rhs.lane_waypoints &&
    lhs.left_waypoints == rhs.left_waypoints &&
    lhs.right_waypoints == rhs.right_waypoints &&
    lhs.good_left == rhs.good_left &&
    lhs.good_right == rhs.good_right &&
    lhs.near_m == rhs.near_m &&
    lhs.straight_lane == rhs.straight_lane &&
    lhs.straight_lane_angle == rhs.straight_lane_angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::utils::Lane3_<ContainerAllocator1> & lhs, const ::utils::Lane3_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::utils::Lane3_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::Lane3_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::Lane3_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::Lane3_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::Lane3_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::Lane3_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::utils::Lane3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7cd779cc732881430cec77cebbd3b445";
  }

  static const char* value(const ::utils::Lane3_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7cd779cc73288143ULL;
  static const uint64_t static_value2 = 0x0cec77cebbd3b445ULL;
};

template<class ContainerAllocator>
struct DataType< ::utils::Lane3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "utils/Lane3";
  }

  static const char* value(const ::utils::Lane3_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::utils::Lane3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"float32 lane_center_offset\n"
"float32 stopline_dist\n"
"float32 stopline_angle\n"
"float32[] lane_waypoints\n"
"float32[] left_waypoints\n"
"float32[] right_waypoints\n"
"bool good_left\n"
"bool good_right\n"
"float32 near_m\n"
"bool straight_lane\n"
"float32 straight_lane_angle\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::utils::Lane3_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::utils::Lane3_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.lane_center_offset);
      stream.next(m.stopline_dist);
      stream.next(m.stopline_angle);
      stream.next(m.lane_waypoints);
      stream.next(m.left_waypoints);
      stream.next(m.right_waypoints);
      stream.next(m.good_left);
      stream.next(m.good_right);
      stream.next(m.near_m);
      stream.next(m.straight_lane);
      stream.next(m.straight_lane_angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Lane3_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::utils::Lane3_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::utils::Lane3_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "lane_center_offset: ";
    Printer<float>::stream(s, indent + "  ", v.lane_center_offset);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "stopline_dist: ";
    Printer<float>::stream(s, indent + "  ", v.stopline_dist);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "stopline_angle: ";
    Printer<float>::stream(s, indent + "  ", v.stopline_angle);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "lane_waypoints: ";
    if (v.lane_waypoints.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.lane_waypoints.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.lane_waypoints[i]);
    }
    if (v.lane_waypoints.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "left_waypoints: ";
    if (v.left_waypoints.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.left_waypoints.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.left_waypoints[i]);
    }
    if (v.left_waypoints.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "right_waypoints: ";
    if (v.right_waypoints.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.right_waypoints.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.right_waypoints[i]);
    }
    if (v.right_waypoints.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "good_left: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.good_left);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "good_right: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.good_right);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "near_m: ";
    Printer<float>::stream(s, indent + "  ", v.near_m);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "straight_lane: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.straight_lane);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "straight_lane_angle: ";
    Printer<float>::stream(s, indent + "  ", v.straight_lane_angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTILS_MESSAGE_LANE3_H
