// Generated by gencpp from file utils/set_states.msg
// DO NOT EDIT!


#ifndef UTILS_MESSAGE_SET_STATES_H
#define UTILS_MESSAGE_SET_STATES_H

#include <ros/service_traits.h>


#include <utils/set_statesRequest.h>
#include <utils/set_statesResponse.h>


namespace utils
{

struct set_states
{

typedef set_statesRequest Request;
typedef set_statesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_states
} // namespace utils


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::utils::set_states > {
  static const char* value()
  {
    return "5e71a6351e81d13c69a7ec3796769e8e";
  }

  static const char* value(const ::utils::set_states&) { return value(); }
};

template<>
struct DataType< ::utils::set_states > {
  static const char* value()
  {
    return "utils/set_states";
  }

  static const char* value(const ::utils::set_states&) { return value(); }
};


// service_traits::MD5Sum< ::utils::set_statesRequest> should match
// service_traits::MD5Sum< ::utils::set_states >
template<>
struct MD5Sum< ::utils::set_statesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::utils::set_states >::value();
  }
  static const char* value(const ::utils::set_statesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::utils::set_statesRequest> should match
// service_traits::DataType< ::utils::set_states >
template<>
struct DataType< ::utils::set_statesRequest>
{
  static const char* value()
  {
    return DataType< ::utils::set_states >::value();
  }
  static const char* value(const ::utils::set_statesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::utils::set_statesResponse> should match
// service_traits::MD5Sum< ::utils::set_states >
template<>
struct MD5Sum< ::utils::set_statesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::utils::set_states >::value();
  }
  static const char* value(const ::utils::set_statesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::utils::set_statesResponse> should match
// service_traits::DataType< ::utils::set_states >
template<>
struct DataType< ::utils::set_statesResponse>
{
  static const char* value()
  {
    return DataType< ::utils::set_states >::value();
  }
  static const char* value(const ::utils::set_statesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UTILS_MESSAGE_SET_STATES_H
