// Generated by gencpp from file utils/set_statesResponse.msg
// DO NOT EDIT!


#ifndef UTILS_MESSAGE_SET_STATESRESPONSE_H
#define UTILS_MESSAGE_SET_STATESRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace utils
{
template <class ContainerAllocator>
struct set_statesResponse_
{
  typedef set_statesResponse_<ContainerAllocator> Type;

  set_statesResponse_()
    : success(false)  {
    }
  set_statesResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::utils::set_statesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::utils::set_statesResponse_<ContainerAllocator> const> ConstPtr;

}; // struct set_statesResponse_

typedef ::utils::set_statesResponse_<std::allocator<void> > set_statesResponse;

typedef boost::shared_ptr< ::utils::set_statesResponse > set_statesResponsePtr;
typedef boost::shared_ptr< ::utils::set_statesResponse const> set_statesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::utils::set_statesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::utils::set_statesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::utils::set_statesResponse_<ContainerAllocator1> & lhs, const ::utils::set_statesResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::utils::set_statesResponse_<ContainerAllocator1> & lhs, const ::utils::set_statesResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::utils::set_statesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::set_statesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::set_statesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::set_statesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::set_statesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::set_statesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::utils::set_statesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::utils::set_statesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::utils::set_statesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "utils/set_statesResponse";
  }

  static const char* value(const ::utils::set_statesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::utils::set_statesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Response\n"
"bool success\n"
"\n"
;
  }

  static const char* value(const ::utils::set_statesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::utils::set_statesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct set_statesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::utils::set_statesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::utils::set_statesResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTILS_MESSAGE_SET_STATESRESPONSE_H
