// Generated by gencpp from file utils/set_statesRequest.msg
// DO NOT EDIT!


#ifndef UTILS_MESSAGE_SET_STATESREQUEST_H
#define UTILS_MESSAGE_SET_STATESREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace utils
{
template <class ContainerAllocator>
struct set_statesRequest_
{
  typedef set_statesRequest_<ContainerAllocator> Type;

  set_statesRequest_()
    : x(0.0)
    , y(0.0)  {
    }
  set_statesRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::utils::set_statesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::utils::set_statesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct set_statesRequest_

typedef ::utils::set_statesRequest_<std::allocator<void> > set_statesRequest;

typedef boost::shared_ptr< ::utils::set_statesRequest > set_statesRequestPtr;
typedef boost::shared_ptr< ::utils::set_statesRequest const> set_statesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::utils::set_statesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::utils::set_statesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::utils::set_statesRequest_<ContainerAllocator1> & lhs, const ::utils::set_statesRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::utils::set_statesRequest_<ContainerAllocator1> & lhs, const ::utils::set_statesRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::utils::set_statesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::set_statesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::set_statesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::set_statesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::set_statesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::set_statesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::utils::set_statesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "209f516d3eb691f0663e25cb750d67c1";
  }

  static const char* value(const ::utils::set_statesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x209f516d3eb691f0ULL;
  static const uint64_t static_value2 = 0x663e25cb750d67c1ULL;
};

template<class ContainerAllocator>
struct DataType< ::utils::set_statesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "utils/set_statesRequest";
  }

  static const char* value(const ::utils::set_statesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::utils::set_statesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request\n"
"float64 x\n"
"float64 y\n"
;
  }

  static const char* value(const ::utils::set_statesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::utils::set_statesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct set_statesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::utils::set_statesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::utils::set_statesRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTILS_MESSAGE_SET_STATESREQUEST_H
