// Generated by gencpp from file utils/waypoints.msg
// DO NOT EDIT!


#ifndef UTILS_MESSAGE_WAYPOINTS_H
#define UTILS_MESSAGE_WAYPOINTS_H

#include <ros/service_traits.h>


#include <utils/waypointsRequest.h>
#include <utils/waypointsResponse.h>


namespace utils
{

struct waypoints
{

typedef waypointsRequest Request;
typedef waypointsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct waypoints
} // namespace utils


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::utils::waypoints > {
  static const char* value()
  {
    return "4b7f567167e5a0533521ec8c8360b4ea";
  }

  static const char* value(const ::utils::waypoints&) { return value(); }
};

template<>
struct DataType< ::utils::waypoints > {
  static const char* value()
  {
    return "utils/waypoints";
  }

  static const char* value(const ::utils::waypoints&) { return value(); }
};


// service_traits::MD5Sum< ::utils::waypointsRequest> should match
// service_traits::MD5Sum< ::utils::waypoints >
template<>
struct MD5Sum< ::utils::waypointsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::utils::waypoints >::value();
  }
  static const char* value(const ::utils::waypointsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::utils::waypointsRequest> should match
// service_traits::DataType< ::utils::waypoints >
template<>
struct DataType< ::utils::waypointsRequest>
{
  static const char* value()
  {
    return DataType< ::utils::waypoints >::value();
  }
  static const char* value(const ::utils::waypointsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::utils::waypointsResponse> should match
// service_traits::MD5Sum< ::utils::waypoints >
template<>
struct MD5Sum< ::utils::waypointsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::utils::waypoints >::value();
  }
  static const char* value(const ::utils::waypointsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::utils::waypointsResponse> should match
// service_traits::DataType< ::utils::waypoints >
template<>
struct DataType< ::utils::waypointsResponse>
{
  static const char* value()
  {
    return DataType< ::utils::waypoints >::value();
  }
  static const char* value(const ::utils::waypointsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UTILS_MESSAGE_WAYPOINTS_H
