// Generated by gencpp from file utils/waypointsRequest.msg
// DO NOT EDIT!


#ifndef UTILS_MESSAGE_WAYPOINTSREQUEST_H
#define UTILS_MESSAGE_WAYPOINTSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace utils
{
template <class ContainerAllocator>
struct waypointsRequest_
{
  typedef waypointsRequest_<ContainerAllocator> Type;

  waypointsRequest_()
    : pathName()
    , vrefName()
    , x0(0.0)
    , y0(0.0)
    , yaw0(0.0)  {
    }
  waypointsRequest_(const ContainerAllocator& _alloc)
    : pathName(_alloc)
    , vrefName(_alloc)
    , x0(0.0)
    , y0(0.0)
    , yaw0(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _pathName_type;
  _pathName_type pathName;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _vrefName_type;
  _vrefName_type vrefName;

   typedef double _x0_type;
  _x0_type x0;

   typedef double _y0_type;
  _y0_type y0;

   typedef double _yaw0_type;
  _yaw0_type yaw0;





  typedef boost::shared_ptr< ::utils::waypointsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::utils::waypointsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct waypointsRequest_

typedef ::utils::waypointsRequest_<std::allocator<void> > waypointsRequest;

typedef boost::shared_ptr< ::utils::waypointsRequest > waypointsRequestPtr;
typedef boost::shared_ptr< ::utils::waypointsRequest const> waypointsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::utils::waypointsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::utils::waypointsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::utils::waypointsRequest_<ContainerAllocator1> & lhs, const ::utils::waypointsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.pathName == rhs.pathName &&
    lhs.vrefName == rhs.vrefName &&
    lhs.x0 == rhs.x0 &&
    lhs.y0 == rhs.y0 &&
    lhs.yaw0 == rhs.yaw0;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::utils::waypointsRequest_<ContainerAllocator1> & lhs, const ::utils::waypointsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::utils::waypointsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::waypointsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::waypointsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::waypointsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::waypointsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::waypointsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::utils::waypointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3ab0a26ea16a690d21406d135bb6ff3b";
  }

  static const char* value(const ::utils::waypointsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3ab0a26ea16a690dULL;
  static const uint64_t static_value2 = 0x21406d135bb6ff3bULL;
};

template<class ContainerAllocator>
struct DataType< ::utils::waypointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "utils/waypointsRequest";
  }

  static const char* value(const ::utils::waypointsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::utils::waypointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request\n"
"string pathName\n"
"string vrefName\n"
"float64 x0\n"
"float64 y0\n"
"float64 yaw0\n"
;
  }

  static const char* value(const ::utils::waypointsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::utils::waypointsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pathName);
      stream.next(m.vrefName);
      stream.next(m.x0);
      stream.next(m.y0);
      stream.next(m.yaw0);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct waypointsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::utils::waypointsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::utils::waypointsRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "pathName: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.pathName);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "vrefName: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.vrefName);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "x0: ";
    Printer<double>::stream(s, indent + "  ", v.x0);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y0: ";
    Printer<double>::stream(s, indent + "  ", v.y0);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "yaw0: ";
    Printer<double>::stream(s, indent + "  ", v.yaw0);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTILS_MESSAGE_WAYPOINTSREQUEST_H
