# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from utils/Lane3.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class Lane3(genpy.Message):
  _md5sum = "7cd779cc732881430cec77cebbd3b445"
  _type = "utils/Lane3"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header

float32 lane_center_offset
float32 stopline_dist
float32 stopline_angle
float32[] lane_waypoints
float32[] left_waypoints
float32[] right_waypoints
bool good_left
bool good_right
float32 near_m
bool straight_lane
float32 straight_lane_angle
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','lane_center_offset','stopline_dist','stopline_angle','lane_waypoints','left_waypoints','right_waypoints','good_left','good_right','near_m','straight_lane','straight_lane_angle']
  _slot_types = ['std_msgs/Header','float32','float32','float32','float32[]','float32[]','float32[]','bool','bool','float32','bool','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,lane_center_offset,stopline_dist,stopline_angle,lane_waypoints,left_waypoints,right_waypoints,good_left,good_right,near_m,straight_lane,straight_lane_angle

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Lane3, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.lane_center_offset is None:
        self.lane_center_offset = 0.
      if self.stopline_dist is None:
        self.stopline_dist = 0.
      if self.stopline_angle is None:
        self.stopline_angle = 0.
      if self.lane_waypoints is None:
        self.lane_waypoints = []
      if self.left_waypoints is None:
        self.left_waypoints = []
      if self.right_waypoints is None:
        self.right_waypoints = []
      if self.good_left is None:
        self.good_left = False
      if self.good_right is None:
        self.good_right = False
      if self.near_m is None:
        self.near_m = 0.
      if self.straight_lane is None:
        self.straight_lane = False
      if self.straight_lane_angle is None:
        self.straight_lane_angle = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.lane_center_offset = 0.
      self.stopline_dist = 0.
      self.stopline_angle = 0.
      self.lane_waypoints = []
      self.left_waypoints = []
      self.right_waypoints = []
      self.good_left = False
      self.good_right = False
      self.near_m = 0.
      self.straight_lane = False
      self.straight_lane_angle = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3f().pack(_x.lane_center_offset, _x.stopline_dist, _x.stopline_angle))
      length = len(self.lane_waypoints)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.lane_waypoints))
      length = len(self.left_waypoints)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.left_waypoints))
      length = len(self.right_waypoints)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.right_waypoints))
      _x = self
      buff.write(_get_struct_2BfBf().pack(_x.good_left, _x.good_right, _x.near_m, _x.straight_lane, _x.straight_lane_angle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.lane_center_offset, _x.stopline_dist, _x.stopline_angle,) = _get_struct_3f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.lane_waypoints = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.left_waypoints = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.right_waypoints = s.unpack(str[start:end])
      _x = self
      start = end
      end += 11
      (_x.good_left, _x.good_right, _x.near_m, _x.straight_lane, _x.straight_lane_angle,) = _get_struct_2BfBf().unpack(str[start:end])
      self.good_left = bool(self.good_left)
      self.good_right = bool(self.good_right)
      self.straight_lane = bool(self.straight_lane)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3f().pack(_x.lane_center_offset, _x.stopline_dist, _x.stopline_angle))
      length = len(self.lane_waypoints)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.lane_waypoints.tostring())
      length = len(self.left_waypoints)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.left_waypoints.tostring())
      length = len(self.right_waypoints)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.right_waypoints.tostring())
      _x = self
      buff.write(_get_struct_2BfBf().pack(_x.good_left, _x.good_right, _x.near_m, _x.straight_lane, _x.straight_lane_angle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.lane_center_offset, _x.stopline_dist, _x.stopline_angle,) = _get_struct_3f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.lane_waypoints = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.left_waypoints = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.right_waypoints = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      _x = self
      start = end
      end += 11
      (_x.good_left, _x.good_right, _x.near_m, _x.straight_lane, _x.straight_lane_angle,) = _get_struct_2BfBf().unpack(str[start:end])
      self.good_left = bool(self.good_left)
      self.good_right = bool(self.good_right)
      self.straight_lane = bool(self.straight_lane)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2BfBf = None
def _get_struct_2BfBf():
    global _struct_2BfBf
    if _struct_2BfBf is None:
        _struct_2BfBf = struct.Struct("<2BfBf")
    return _struct_2BfBf
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
